### ISSUE TITLE
event.preventDefault() not working

### ISSUE THREAD

**Issue by swannknani** [vuejs/vue-touch#11]
Hi,

`event.preventDefault()` is actually not stopping the normal behaviour when clicking on a link.
Having check on Hammer.js website, I don't think I'm doing it wrong - tell me if you can't reproduce it.

**Comment by sinoon** [comment]
same problem 
hammer: 2.0.1
vue.touch: 0.1.1rc3

**Comment by adriaanmeuris** [comment]
I can confirm this issue. Any update or directives how to solve this?

**Comment by LinusBorg** [comment]
See Tips&Tricks on the hammer docs about preventing the "ghost click"
