### ISSUE TITLE
how to prevent parent gestures of overlapping child gestures

### ISSUE THREAD

**Issue by ctf0** [vuejs/vue-touch#112]
lets say you have 2 components , with each have its own `swipeLeft / swipeRight`

now because both have the same events, so it means that sometimes when u try to trigger the child component event, the parent will fire too & sometime it would even overlap the child.

so is there a way to set like a boundaries with higher order for each nested component, so that the child events doesnt bubble up to the parent/wrapper component ?

of course this means that if the child component is as big as the parent `position: absolute / fixed` , you won't be able to trigger the parent touch events, but that would be the expected.

**Comment by minedun6** [comment]
usually the behaviour is the same with the click event when parent/child have a click binded event.
normally I do "stopPropagation".

**Comment by ctf0** [comment]
u mean something like `@swipeleft.stop="..."` ?

**Comment by minedun6** [comment]
yeah something like that.
