### ISSUE TITLE
How to pass parameters into the function?

### ISSUE THREAD

**Issue by Voyga** [vuejs/vue-touch#16]
`v-touch="press: func()"` => `func()` will be excuted after the page is loaded, and the press event is not working.
but `v-touch="press: func"` works fine.

Then how to pass parameters?

**Comment by Crimx** [comment]
@Voyga Why would you need to pass parameters to a event function?

**Comment by Crimx** [comment]
@Voyga Why would you need to pass parameters to an event function?

**Comment by brycehanscomb** [comment]
@Crimx, a common example is passing the index of the actioned element (eg: element n of a list)

**Comment by Crimx** [comment]
@brycehanscomb then I would access `event.target` and get it from the element itself

**Comment by herbertpimentel** [comment]
I have been using like so, but I am really curious about it and maybe that way I do is not a good practice. 

```html

<ul v-for="pessoa in pessoas">
  <li>
    <a href="#" v-on:click="showPessoa(pessoa)">{{ pessoa.nome }}</a>
  </li>
</ul>
```


```javascript
    // ...
    methods : {
        showPessoa : function(pess){
            console.log(pess);
            alert(pess.nome);
        }
    }
```

**Comment by kamifun** [comment]
If you not neet the $event argument，you can do this:
`v-touch:press="func.bind(this, arg)"`

**Comment by AdrianKuriata** [comment]
Hi, i have something like this:

`v-on:click="removeRelation({{$people->id}}, relation.people['id'])"`

I have a problem with get a target from this. This is my function for Vue:

```
removeRelation: function($peopleId, $relatedId) {
		//do something
	}
```

Is possible to get clicked element with arguments? I tried add this to html **v-on:click** like a third argument and try to display it with **thirdArgument.target**, but i getting undefined into console.

**Comment by bognix** [comment]
Something like this worked for me just fine.
```
<foo @click="(event) => { showSlide(event, myArgument) } ></foo>
```
Hope it helps

**Comment by AdrianKuriata** [comment]
@bognix this is not clear code, check post before your, i added solution.

**Comment by bognix** [comment]
cool! thanks for posting, I missed the link

**Comment by wu08518** [comment]
understand
