### ISSUE TITLE
`vue-touch`@0.1.2 not compatible with `vue`@1.0.4?

### ISSUE THREAD

**Issue by dickeylth** [vuejs/vue-touch#20]
![image](https://cloud.githubusercontent.com/assets/2196373/10874240/099fe2b4-815c-11e5-9487-01aa8bbe5166.png)
As shown in the figure, under `vue-touch` directory and execute `npm run dev`, browse the `example.html` and then the browser caught an error.

Environment:
- System: OS X El Capitan 10.11.1 (15B42)
- Chrome: 46.0.2490.80 (64-bit)
- node: v0.12.7

**Comment by yyx990803** [comment]
This is pretty out dated. Will need a rewrite some time.

**Comment by dickeylth** [comment]
So the suggestion is using `vue`@~0.12? I'm helping build the front-end infrastructure in out team which is focusing on Hybrid app development, and handling `touch` is essential in most situations. I'm interested in bringing in `webpack` + `vue.js` into our workflow, and really much appreciated to see the upgrade version of `vue-touch` compatible with `vue`@^1.0.

**Comment by OlliM** [comment]
For me it worked by using the directive like this:

v-touch:swipe="doSwipe"

**Comment by roblav96** [comment]
OMG I <3 U!!!!!!!!

**Comment by dickeylth** [comment]
@OlliM Yes I also figured out this works, thank you!

**Comment by 3stacks** [comment]
Please see https://github.com/vuejs/vue-touch/pull/23 if you're still having trouble. I now have it working well in Vue 1.x.

**Comment by roblav96** [comment]
@3stacks I three love u
