### ISSUE TITLE
Android touch delay

### ISSUE THREAD

**Issue by robin7331** [vuejs/vue-touch#24]
If I use vue-touch in a mobile project everything works fine in iOS. The problem is, if we use the same code on android the touches (especially a :active css class) will show up about 200ms after the actual touch. 

Do you know why?

Thanks!

**Comment by brunocascio** [comment]
Hi @robin7331, i reduced de delay of `press` event overriding the options. (i don't know what event you talking about)

```js
 VueTouch.registerCustomEvent('press', {
   type: 'press',
   time: 100 
});
```

Check [hammer documentation](http://hammerjs.github.io/recognizer-press/) for more info.

**Comment by LinusBorg** [comment]
also have a look at hammer-time here: https://hammerjs.github.io/

which aims to remove the typical click delay on touch devices.
