### ISSUE TITLE
Can't scroll on iOS

### ISSUE THREAD

**Issue by Johnathan** [vuejs/vue-touch#28]
Using `swipeleft`is stopping the container it's applied to from scrolling the content inside it. Is there a way around this? I assume it's because hammer is picking up all the swipe/scroll events and not letting the browser handle them?

```
    <div class="menu animated" v-bind:class="menuClass" v-touch:swipeleft="closeMenu">
        <div class="menu-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium asperiores beatae dolorem ea
                eligendi, esse, ipsam laboriosam molestiae molestias nam omnis quam quidem rem reprehenderit soluta
                veniam voluptatum. Facere, necessitatibus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium asperiores beatae dolorem ea
                eligendi, esse, ipsam laboriosam molestiae molestias nam omnis quam quidem rem reprehenderit soluta
                veniam voluptatum. Facere, necessitatibus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium asperiores beatae dolorem ea
                eligendi, esse, ipsam laboriosam molestiae molestias nam omnis quam quidem rem reprehenderit soluta
                veniam voluptatum. Facere, necessitatibus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium asperiores beatae dolorem ea
                eligendi, esse, ipsam laboriosam molestiae molestias nam omnis quam quidem rem reprehenderit soluta
                veniam voluptatum. Facere, necessitatibus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium asperiores beatae dolorem ea
                eligendi, esse, ipsam laboriosam molestiae molestias nam omnis quam quidem rem reprehenderit soluta
                veniam voluptatum. Facere, necessitatibus.</p>
        </div>
    </div>
```

That's the CSS properties being applied from vue-touch/hammer

```
    touch-action: none;
    -webkit-user-select: none;
    -webkit-user-drag: none;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```

**Comment by yyx990803** [comment]
Probably related: http://hammerjs.github.io/touch-action/

**Comment by BrandonSurowiec** [comment]
@Johnathan @yyx990803  Did you figure out a solution? I know the `touch-action` should be set to `pan-y` but I haven't figured out how to pass that into the element to override. Looks like `options.behavior.touchAction` is what needs to be set.

**Comment by Johnathan** [comment]
I didn't. I ended up just changing the "panel" that could be swiped. Not ideal but something I can look at later on.

**Comment by andre-dw** [comment]
Is there a fix for this now?

**Comment by tilleps** [comment]
I might have I figured it out:

```javascript
VueTouch.config.swipe = {
  direction: 'horizontal'
};
Vue.use(VueTouch);
```

http://hammerjs.github.io/recognizer-swipe/

> When calling Hammer() to create a simple instance, the pan and swipe recognizers are configured to only detect horizontal gestures.

**Comment by tilleps** [comment]
Applying options on the element appears to also work:

```html
<a
  v-touch:swipe="onSwipe"
  v-touch-options:swipe="{ direction: 'horizontal' }">
</a>
```

**Comment by JamieBunyassi** [comment]
For vue-touch@next the following works v-on:swipeleft="swipeLeft" v-on:swiperight="swipeRight" v-bind:swipe-options="{ direction: 'horizontal' }"

**Comment by nbursa** [comment]
1. Make v-touch component empty sibling element to its content.
2. Position it absolutely full screen and add CSS pointer-events: none
3. Add to it tap event listener and toggle hide only on tap
4. On underlying content add CSS pointer-events: all and toggle show v-touch on tap.
