### ISSUE TITLE
当绑定了swipeleft, swiperight事件，滚动失效!

### ISSUE THREAD

**Issue by HenryHyt** [vuejs/vue-touch#41]
当使用 v-touch:swipeleft,  v-touch:swiperight 绑定了事件，原生的页面滚动就失效了

**Comment by coder-Yin** [comment]
+1

**Comment by zousandian** [comment]
可以在发 issue 前先搜一下 https://github.com/vuejs/vue-touch/issues/28

**Comment by coder-Yin** [comment]
谢谢 已解决，下次注意

**Comment by MrRenyj** [comment]
两种解决办法:
1.在全局配置中加上VueTouch.config.swipe = {direction: 'horizontal' }
2.在使用vue-touch的元素上直接加上 v-touch-options:swipe="{ direction:'horizontal'}"
例如:<div class="content"  v-touch:swiperight="changeTab(0)"  v-touch-options:swipe="{ direction:'horizontal'}">

**Comment by MrRenyj** [comment]
<div class="content" v-touch:swiperight="changeTab(0)"  v-touch-options:swipe="{direction:'horizontal'}"></div>
