### ISSUE TITLE
vue-touch still not compatible with Vue 2.0

### ISSUE THREAD

**Issue by rse** [vuejs/vue-touch#44]
Now that Vue 2.0 is in release-candidate status and hence its API fixed, can you please add support for Vue 2.0 to your vue-touch plugin? Thanks for your efforts.

**Comment by Eiskis** [comment]
Same here, like many others I'm sure I'm starting to migrate an in-development project to Vue 2.0 as it's already on RC2. Vue Router has a 2.0 RC as well so eagerly waiting for this guy to get the same treatment. `vue-touch.js` is 165 lines of code so it's kinda silly to have this as the thing that's blocking migration efforts.

**Comment by chrisvfritz** [comment]
This is now in progress thanks to @LinusBorg. @Eiskis Releasing and coordinating new versions for an entire ecosystem is a monumental effort, so patience is appreciated.

**Comment by LinusBorg** [comment]
>  @Eiskis Releasing and coordinating new versions for an entire ecosystem is a monumental effort, so patience is appreciated.

...and no one is keeping you from creating a pull request yourself ;)

**Comment by Eiskis** [comment]
Great news, thanks for the update.

**Comment by maicong** [comment]
please!!!

**Comment by LinusBorg** [comment]
the `next`branch is already 2.0 compatible, we just have to release to npm. Please be patient for a little while longer.

**Comment by chrisvfritz** [comment]
For anyone that really needs to use this before it's published, you can install the 2.0-compatible version with: 

``` sh
npm install --save git://github.com/vuejs/vue-touch.git#next
```

**Comment by vinayakkulkarni** [comment]
It's 2017 already. 😃

**Comment by LinusBorg** [comment]
https://github.com/vuejs/vue-touch/releases/tag/2.0.0-beta.3
