### ISSUE TITLE
Throw error on dynamic configuration.

### ISSUE THREAD

**Issue by JounQin** [vuejs/vue-touch#45]
I want to only enable `vue-touch` when using `mobile mode`, but for now I haven't found any solution to that, so I try to use `v-if` and `v-else` to specific different modes.

My Code:

``` vue
        <calendar v-if="mode"
                  v-touch:panstart="onPanStart"
                  v-touch:pan="onPan"
                  v-touch:panend="onPanEnd"
                  :calendar="calendar"
                  :activeDate="activeDate"
                  :translateX="translateX"
                  @toggleActiveDate="toggleActiveDate"
                  @transitionend.native.self="onTransitionEnd"/>
        <calendar v-else
                  :calendar="calendar"
                  :activeDate="activeDate"
                  :translateX="translateX"
                  @toggleActiveDate="toggleActiveDate"/>
```

`mode` is a dynamic value, and when I resize the window, it will change, once `vue-touch` is enabled and then resize window to change `mode`, it will throw an error.

```
Uncaught TypeError: Cannot read property 'mc' of null
```

Reproduction: http://hi.1stg.me/#/member-subscribe

How to reproduce:
Just open the console and then resize the window size.

Besides, is there any way to enable or disable `vue-touch` dynamically?

**Comment by LinusBorg** [comment]
I will close this because 2.0.0-beta is now a complete rewrite. 

Feel free to open a new issue if you have problems.
