### ISSUE TITLE
Tap unexpectedly handled by radio button just appeared by same tap event

### ISSUE THREAD

**Issue by ypresto** [vuejs/vue-touch#47]
Version: 1.1.0
Reproduction: https://github.com/ypresto/vue-touch-appeared-radio-bug

![screencast](https://cloud.githubusercontent.com/assets/400558/18581771/ffdd5e5a-7c3c-11e6-868a-590b148a237e.gif)
1. Create v-touch:tap element and radio buttons.
2. Implement tap handler method which shows initially hidden radio buttons and hides tapped element.
3. Tap the v-touch:tap element.
4. The radio button which appeared on tapped position will be selected.

Workaround: Wrap v-touch:tap handler with `setTimeout(..., 0)`.

**Comment by LinusBorg** [comment]
Closing this because it's too old and likely not a problem with version 2.0.0.

If the problem persists, please open another issue.
