### ISSUE TITLE
prevent default

### ISSUE THREAD

**Issue by z1haze** [vuejs/vue-touch#55]
I started using this plugin because I had a problem on iphones where i had an anchor that had a hover event , and a click event. So in that case the during the first 'click' on the iphone it only activated the hover event, so users would have to in a sense double click to activate the click - this plugin seemed to fix that.

But when using an @click along side v-touch, it fires the events twice on desktop, it will fire the touch event, and the click event. I tried adding .prevent to the v-touch call, but it didnt do anything. Is this supposed to be able to prevent default action with touch events?

**Comment by z1haze** [comment]
seems there is a 'ghost click' that is fired by the browsers? how do we handle that so as to not trigger the same function twice?

**Comment by deltragon** [comment]
That's a problem with Hammer.js itself, there is a workaround: 
http://hammerjs.github.io/tips/ and https://gist.github.com/jtangelder/361052976f044200ea17
