### ISSUE TITLE
#next branch bug: guardDirections not called on registered custom events

### ISSUE THREAD

**Issue by timothyhague** [vuejs/vue-touch#56]
Hello,

On the #next branch, when you register a custom event with a **direction** option, it breaks things.

So, for example, if you register this:

VueTouch.registerCustomEvent('panhorizontal', {
  type: 'pan',
  direction: 'horizontal',
  threshold: 100,
});

Then use it like:

`<div v-touch:panhorizontal="onPanHorizontal">content</div>`

No pan event is fired.

The reason for this is because this function:

[guardDirections](https://github.com/vuejs/vue-touch/blob/next/vue-touch.js#L154)

is not being called in [this block](https://github.com/vuejs/vue-touch/blob/next/vue-touch.js#L43).

...meaning the 'horizontal' string in the options is never translated to the integer it has to be for it to work.

**Comment by LinusBorg** [comment]
@timothyhague  I re-wrote the next branch as a component: 

https://github.com/vuejs/vue-touch/releases/tag/2.0.0-beta.1
