### ISSUE TITLE
When to support version vuejs 2.0 ?

### ISSUE THREAD

**Issue by syaka-yin** [vuejs/vue-touch#58]
hello, guys, When to support version vuejs 2.0 ?

**Comment by hoipo** [comment]
There is anohter brance named "next", that can support 2.0
[](https://github.com/vuejs/vue-touch/tree/next)

**Comment by Leungkingman** [comment]
which version should i install when i use npm?

**Comment by Beatusvir** [comment]
@Leungkingman according to [this](https://github.com/vuejs/vue-touch/issues/44) You can use
`npm install --save git://github.com/vuejs/vue-touch.git#next`

**Comment by Leungkingman** [comment]
@Beatusvir It doesn't work in vue2.0,have you made it ?

**Comment by Leungkingman** [comment]
@hoipo Hi,could you tell me how to use vue-touch in vue2.0 please?
here are my code:
`import Vue from 'vue'
import App from './App';
import VueResource from 'vue-resource'
import VueTouch from 'vue-touch'

import _ from 'lodash'
import echarts from 'echarts'
import Mint from 'mint-ui'
import Moment from 'moment'
import filter from './assets/filter'

window.echarts = echarts
window.Moment = Moment
window._ = _

Vue.use(VueResource)
Vue.use(VueTouch)
Vue.use(Mint)`


`<div class="inline c-lightGray" :class="{'bor-b-deepBlue c-deepBlue': machineTableShowType.notStopShow }" v-touch:tap="openMachineTable('notStop')">非停机组({{notStopDataNum}})</div>`

once i run the project , there is an warn and serval errors
vue.js?3de6:2643 [Vue warn]: Error when rendering component <App> at /Users/honghaiweb/Desktop/Web Project/CRPower_SVN/crp-log/src/components/App.vue: 

if i don't use the direactive of v-touch:tap,everything goes well

**Comment by Beatusvir** [comment]
Yes I got it working. Installed it as I mentioned before:
`npm i -S git://github.com/vuejs/vue-touch.git#next`

And used it as you did, anything else on the error?

**Comment by LinusBorg** [comment]
FYI, I published v2.0.0-beta.1, compatible with Vue 2.0:

https://github.com/vuejs/vue-touch/releases/tag/2.0.0-beta.1

Heds up: `vue-touch` is now a component instead of a directive, so some migration work is nessessary.

I will close this issue. If you have problems with the new version, please open a new issue.
