### ISSUE TITLE
Using the next branch cause errors with server side rendering

### ISSUE THREAD

**Issue by pajtai** [vuejs/vue-touch#66]
Getting the following error on the next branch:

```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

code looks like:

```
        <div class="overflow" >
            <v-touch class="inner"
                 :style="innerStyle"
                 v-on:swipeleft="next"
                 v-on:swiperight="prev" >
                <slot></slot>
            </v-touch>
        </div> 
```

I know it's the `v-touch` component causing the error, since when I delete the component, the error goes away.

**Comment by LinusBorg** [comment]
Can you provide a repository with a reproduction of this problem, please? 

Thanks!

**Comment by LinusBorg** [comment]
It seems even just requiring Hammer on the server is creating trouble during server-side rendering, so I will have to see what I can do about that at all.

**Comment by LinusBorg** [comment]
I think a possible solution would be to provide a stubbed version of `v-touch` with the package. This stub would basically be a functionless component expect for the `tag` prop, and it would not not require Hammer (there's no use for it on the server anyway). 

The user can then use a webpack alias in his SSR webpack config to load this in place of the normal module:

`'vue-touch$': 'vue-touch/stub.js'`

**Comment by pajtai** [comment]
Yeah the issue might be that I stubbed out all of vue touch on the server. I'm use webpack aliases to have separate server and client side versions. Now that I think about it, that would make sense as to the cause of the problem.

I will try and send you a repo to show what I'm doing, but might take a while, since this is gonna be a busy work week.

Thanks for starting to look into it.

**Comment by LinusBorg** [comment]
@pajtai I don't think the repo is nessessary anymore, already working on the solution.

**Comment by LinusBorg** [comment]
Now available in [v2.0.0-beta.2](https://github.com/vuejs/vue-touch/releases/tag/2.0.0-beta.2)

**Comment by gokhanozdemir** [comment]
Hello,

I have embeded with the ssr workaround to the vue next.js. The stuff is working however it brokes the DOM and I am getting 'the client-side rendered virtual DOM tree is not matching server-rendered content...' 

using beta-4

**Comment by LinusBorg** [comment]
Please open an issue and provide a reproduction.
