### ISSUE TITLE
Pass options to Hammer constructor

### ISSUE THREAD

**Issue by deltragon** [vuejs/vue-touch#68]
I would like to use swipe with touch inputs only (cause mouse inputs tend to be somewhat buggy), but I can't pass options to the Hammer constructor (as recommended here: [link](http://stackoverflow.com/a/35484097)).
I'm using Vue 2.0 and vue-touch@next

**Comment by deltragon** [comment]
Workaround:
`import Hammer from 'hammerjs'`
`Hammer.defaults.inputClass = Hammer.TouchInput;`
This works, but passing options would still be nice

**Comment by LinusBorg** [comment]
That should be doable.

**Comment by LinusBorg** [comment]
@deltragon added in 2.0,0-beta.3
