### ISSUE TITLE
does it support  stopPropagation() in vue-touch 2.0 

### ISSUE THREAD

**Issue by dericgit** [vuejs/vue-touch#69]
@tap.stop and @tap="demoMethod($event)"  $event.stopPropagation()

it is error that dose not find stopPropagation method

 after @tap pass $event is not primary MouseEvent

**Comment by LinusBorg** [comment]
> @tap.stop and @tap="demoMethod($event)" $event.stopPropagation()

I think your problem is the so-called "ghost click" that happens with tap events. Please see here:

https://hammerjs.github.io/tips/ (end of page)

> after @tap pass $event is not primary MouseEvent

Because HammerJS does not emit a MousEvent, it emits a Hammer event. If you want / need a mouse event, this libary is not for you.
