### ISSUE TITLE
Error SSR with v2.0.0-beta.3

### ISSUE THREAD

**Issue by ram-you** [vuejs/vue-touch#71]
I have the error on ssr :
`ReferenceError: window is not defined`
using v2.0.0-beta.3

**Comment by LinusBorg** [comment]
Those are two different errors, hence why I asked for separate issues. Feel free to open another issue for the second problem.

**Comment by LinusBorg** [comment]
Source of the error her:

https://github.com/vuejs/vue-touch/blob/next/src/index.js#L41

solution: check if window is undefined beforehand.

**Comment by LinusBorg** [comment]
hopefully solved in 2.0.0-beta.4
