### ISSUE TITLE
Cannot set property 'exports' of undefined

### ISSUE THREAD

**Issue by jackmellis** [vuejs/vue-touch#75]
I've recently started getting this error with vue-touch. I'm using webpack 2 / vue 2. It works fine in development, but when I create my production build, I get this error.

It looks like the `module` variable (renamed to `t` by webpack's uglifier) is being overwritten in the main anonymous method's `global`.

I suppose that a simple global 'use strict' somewhere in the application would prevent the `global` object being passed in. I think webpack is forcing strict mode because when I removed the `-p` flag (but kept the uglifier etc. switched on) it works fine.

![image](https://cloud.githubusercontent.com/assets/12736176/24504855/b2220a2e-154f-11e7-9b84-fd34182b8cfd.png)  
...  
![image](https://cloud.githubusercontent.com/assets/12736176/24504862/c468d4ba-154f-11e7-9ce8-c91e7404e3c3.png)

**Comment by MikaelEdebro** [comment]
Is there any solution to this? I'm getting the same error. Removing -p from webpack command helps, but this is not optimal.

**Comment by jackmellis** [comment]
@MikaelEdebro this will quite a while ago but I think I got around this in the end by using `vue-touch/dist/vue-touch.min.js` rather than just `vue-touch`

**Comment by aziev** [comment]
@jackmellis thied `vue-touch/dist/vue-touch.min.js` and it has the same behavior
