### ISSUE TITLE
Uncaught TypeError: Cannot read property 'priority' of undefined

### ISSUE THREAD

**Issue by covertbert** [vuejs/vue-touch#96]
I get this error immediately after I `require` and `Vue.use` the directive. It appears to be referring to  `Vue.directive('on')` within the plugin but I can't figure out exactly what the issue is.

I'm using the Quasar Vue platform

**Comment by LinusBorg** [comment]
You are using the Vue 1 version with vue 2.
```
npm install vue-touch@next
```

gives you the Vue2 version.

We have been meaning to release this as the default for ages, but it always falls through the cracks unfortunately :(

**Comment by covertbert** [comment]
Nice one, cheers mate!
